// packages/cliqz-home-react/src/UrlBar.js
import React, { Component } from 'react';
import cliqz from './Cliqz';

const SPECIAL_KEYS = [8, 9, 13, 16, 17, 18, 19, 20, 27, 33, 34, 35, 36, 37, 38, 39, 40, 91, 224];

class UrlBar extends Component {
  constructor(props) {
    super(props);
    this.state = {
      value: '',
      locale: ''
    };

    this.handleKeyDown = this.handleKeyDown.bind(this);
  }

  componentDidMount() {
    this.getConfig();
    this.textInput.focus();
  }

  componentDidUpdate() {
    window.urlbarReady();
  }

  getConfig() {
    this.props.freshtab.getConfig()
      .then((config) => {
        this.setState(Object.assign({}, this.state, {
          locale: config.locale
        }));
      });
  }

  handleKeyDown(ev) {
    const value = ev.target.value;
    let input = SPECIAL_KEYS.indexOf(ev.which) > -1 ? '' : ev.key;
    this.setState(Object.assign({}, this.state, {
      value: value
    }));
    if(ev.keyCode === 13) {
      input = value;
    }
    cliqz.core.queryCliqz(input);

    cliqz.core.sendTelemetry({
      type: 'home',
      action: 'search_keystroke'
    });

    setTimeout(() => {
      this.textInput.value = '';
    }, 0);
  }

	render() {
		return (
			<div>
				<input className="url-bar" 
               type="text"
               ref={(input) => { this.textInput = input; }}
               placeholder="search"
               onKeyDown={this.handleKeyDown}
               role={this.state.locale} />
			</div>
		);
	}
}

export default UrlBar;

// packages/cliqz-home-vue/src/components/freshtab/UrlBar.vue
<template>
  <input class="url-bar" v-model="value" ref='search' v-on:keydown="queryCliqz" placeholder="Search or enter address" :locale="locale"></input>
</template>

<script>
export default {
  name: 'url-bar',
  props: ['core', 'locale'],
  data () {
    return {
      value: ''
    }
  },
  created () {
    this.SPECIAL_KEYS = [8, 9, 13, 16, 17, 18, 19, 20, 27,
      33, 34, 35, 36, 37, 38, 39, 40, 91, 118, 224]
    this.queryCliqz.bind(this)
  },
  mounted () {
    window.urlbarReady()
    this.$el.focus()
  },
  methods: {
    queryCliqz (ev) {
      let input = this.SPECIAL_KEYS.indexOf(ev.which) > -1 ? '' : ev.key

      if (ev.keyCode === 13) {
        input = this.value
      }

      this.core.queryCliqz(input)

      this.core.sendTelemetry({
        type: 'home',
        action: 'search_keystroke'
      })

      setTimeout(() => {
        this.value = ''
      }, 0)
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss" scoped>
@import './src/assets/styles/variables.scss';
.url-bar {
  box-sizing: border-box;
  display: block;
  width: $content-width;
  margin: 0 auto;
  border: 1px solid #DBDBDB;
  font-size: 16px;
  height: 35px;
}
</style>
