// packages/cliqz-home-react/src/App.js
import React, { Component } from 'react';
import './App.css';
import UrlBar from './UrlBar';
import SpeedDials from './SpeedDials';
import News from './News';
import Spanan from 'spanan';

let freshtabSpanan;
let coreSpanan;
class App extends Component {
  constructor(props) {
    super(props); 
    window.addEventListener('message', this.handleMessage);
    freshtabSpanan = this.createSpananForModule('freshtab');
    coreSpanan = this.createSpananForModule('core');
    this.freshtab = freshtabSpanan.createProxy();
    this.core = coreSpanan.createProxy();
  }

  render() {
    return (
      <div id="app">
        <div id="home">
          <nav id="nav-left"></nav>
          <section id="content">
            <section id="top">
              <SpeedDials freshtab={this.freshtab} />
            </section>

            <section id="middle">
              <UrlBar />
            </section>

            <section id="bottom">
              <News freshtab={this.freshtab} />
            </section>
          </section>
        </div>
      </div>
    );
  }

  createSpananForModule (moduleName) {
    return new Spanan(({ uuid, functionName, args }) => {
      const message = JSON.stringify({
        target: 'cliqz',
        module: moduleName,
        action: functionName,
        requestId: uuid,
        args
      })
      window.postMessage(message, '*')
    });
  }

  handleMessage(event) {

    const message = JSON.parse(event.data)
    if (message.type !== 'response') {
      return;
    }
    freshtabSpanan.dispatch({
      uuid: message.requestId,
      returnedValue: message.response
    })

    coreSpanan.dispatch({
      uuid: message.requestId,
      returnedValue: message.response,
    });
  }

}

export default App;

// packages/cliqz-home-vue/src/components/App.vue
<template>
  <div id="app">
    <home :freshtab="freshtab" :core="core"></home>
  </div>
</template>

<script>
import Spanan from 'spanan'
import Home from './freshtab/Home.vue'
export default {
  name: 'app',
  components: { Home },
  data () {
    return {
      freshtab: {},
      core: {}
    }
  },
  created () {
    this.handleMessage = this.handleMessage.bind(this)
    this.freshtabSpanan = this.createSpananForModule('freshtab')
    this.coreSpanan = this.createSpananForModule('core')
    window.addEventListener('message', this.handleMessage)
    this.freshtab = this.freshtabSpanan.createProxy()
    this.core = this.coreSpanan.createProxy()
  },
  destroyed () {
    window.removeEventListener('message', this.handleMessage)
  },
  methods: {
    handleMessage (event) {
      const message = JSON.parse(event.data)

      if (message.type !== 'response') {
        return
      }

      this.freshtabSpanan.dispatch({
        uuid: message.requestId,
        returnedValue: message.response
      })

      this.coreSpanan.dispatch({
        uuid: message.requestId,
        returnedValue: message.response
      })
    },
    createSpananForModule (moduleName) {
      return new Spanan(({ uuid, functionName, args }) => {
        const message = JSON.stringify({
          target: 'cliqz',
          module: moduleName,
          action: functionName,
          requestId: uuid,
          args
        })
        window.postMessage(message, '*')
      })
    }
  }
}
</script>

<style lang="scss" scoped>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
